import { useState } from 'react';
import { AuditResult } from '@/types/audit';
import { LeadFormData } from '@/types/lead';
import { getOpportunityLevel, getOpportunityLabel, getOpportunityColor } from '@/lib/opportunity';
import { Button } from '@/components/ui/button';
import { MessageCircle, Send, Mail, CalendarCheck, CheckCircle2, AlertTriangle, Loader2 } from 'lucide-react';
import { cn } from '@/lib/utils';
import { supabase } from '@/integrations/supabase/client';
import { toast } from '@/hooks/use-toast';

interface Props {
  result: AuditResult;
  lead: LeadFormData | null;
}

const WHATSAPP_NUMBER = '447451250738';
const SUPPORT_EMAIL = 'webauditproteam@gmail.com';

export const AuditSummaryCTA = ({ result, lead }: Props) => {
  const [sendingTelegram, setSendingTelegram] = useState(false);
  const level = getOpportunityLevel(result.overallScore);
  const isAgency = lead?.user_type === 'agency';
  const brandedBy = isAgency ? (lead?.agency_name || 'Your Agency') : 'Web Audit Pro';
  const supportMessage = `Hi there! 👋\n\nI just reviewed my Comprehensive Website Audit Report for ${result.domain}. The report flagged issues across SEO, performance, security, conversion, and overall website optimization.\n\nWebsite Score: ${result.overallScore}/100\n\nI'm interested in starting Phase 1 (Website Optimization). Please walk me through the first 30 days, turnaround time, pricing, and what results or benchmarks I can expect once the fixes are live.\n\nLooking forward to hearing from you.`;
  const encodedSupportMessage = encodeURIComponent(supportMessage);
  const whatsappUrl = `https://api.whatsapp.com/send?phone=${WHATSAPP_NUMBER}&text=${encodedSupportMessage}`;
  const reportUrl = typeof window !== 'undefined' ? window.location.href : `https://${result.domain}`;
  const emailUrl = `mailto:${SUPPORT_EMAIL}?subject=${encodeURIComponent(`Comprehensive Website Audit Report — ${result.domain}`)}&body=${encodedSupportMessage}`;

  const handleTelegram = async () => {
    setSendingTelegram(true);
    try {
      const { error } = await supabase.functions.invoke('notify-telegram', {
        body: {
          domain: result.domain,
          score: result.overallScore,
          reportUrl,
          name: lead?.full_name,
          contact: [lead?.email, lead?.whatsapp].filter(Boolean).join(' · '),
          note: `Visitor wants to start Phase 1 (Website Optimization). Please reach out to them directly.`,
        },
      });
      if (error) throw error;
      toast({ title: 'Sent on Telegram', description: 'Your request has been delivered. Expect a reply within 24h.' });
    } catch (e) {
      toast({ title: 'Could not send', description: (e as Error).message, variant: 'destructive' });
    } finally {
      setSendingTelegram(false);
    }
  };

  const topIssues = [...result.issues]
    .filter((i) => ['critical', 'error'].includes(i.severity))
    .sort((a, b) => (b.revenueLoss || 0) - (a.revenueLoss || 0))
    .slice(0, 5);

  const quickWins = [...result.issues]
    .filter((i) => i.priority === 'high' && i.severity !== 'info')
    .slice(0, 5);

  return (
    <div className="space-y-6">
      {/* Hero summary */}
      <div className="glass-card rounded-2xl border-2 border-primary/30 p-6 md:p-8 text-center">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-success/15 text-success text-xs font-semibold uppercase tracking-wider mb-3">
          <CheckCircle2 className="w-3.5 h-3.5" />
          Your Audit Report is Ready
        </div>
        <h2 className="text-3xl md:text-4xl font-bold mb-3">{result.domain}</h2>
        <div className="flex flex-col sm:flex-row items-center justify-center gap-6 mt-4">
          <div>
            <div className="text-6xl font-bold gradient-text">{result.overallScore}</div>
            <div className="text-xs text-muted-foreground mt-1">Website Score / 100</div>
          </div>
          <div className={cn('px-5 py-3 rounded-xl border-2 font-semibold', getOpportunityColor(level))}>
            {getOpportunityLabel(level)}
          </div>
        </div>
        <p className="text-xs text-muted-foreground mt-4">Generated By: {brandedBy}</p>
      </div>

      {/* Top issues + quick wins */}
      <div className="grid md:grid-cols-2 gap-4">
        <div className="glass-card rounded-xl border border-border/50 p-5">
          <h3 className="font-semibold mb-3 flex items-center gap-2">
            <AlertTriangle className="w-4 h-4 text-destructive" /> Top Issues Found
          </h3>
          <ul className="space-y-2 text-sm">
            {topIssues.length ? topIssues.map((i) => (
              <li key={i.id} className="flex gap-2"><span className="text-destructive">•</span><span>{i.title}</span></li>
            )) : <li className="text-muted-foreground text-sm">No critical issues 🎉</li>}
          </ul>
        </div>
        <div className="glass-card rounded-xl border border-border/50 p-5">
          <h3 className="font-semibold mb-3 flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 text-success" /> Quick Wins
          </h3>
          <ul className="space-y-2 text-sm">
            {quickWins.length ? quickWins.map((i) => (
              <li key={i.id} className="flex gap-2"><span className="text-success">•</span><span>{i.recommendation || i.title}</span></li>
            )) : <li className="text-muted-foreground text-sm">Keep scrolling for full details.</li>}
          </ul>
        </div>
      </div>

      {/* CTA */}
      {!isAgency && (
        <div className="relative overflow-hidden rounded-2xl border-2 border-primary/40 bg-gradient-to-br from-primary/15 via-background to-info/10 p-6 md:p-8">
          <div className="text-center max-w-2xl mx-auto space-y-4">
            <h3 className="text-2xl md:text-3xl font-bold">Need Help Fixing These Issues?</h3>
            <p className="text-muted-foreground">We can help you improve SEO, conversion rate, website speed, store redesign, and full optimization.</p>
            <div className="flex flex-col sm:flex-row gap-3 justify-center pt-2">
              <Button asChild size="lg" className="bg-[#25D366] hover:bg-[#1ebe57] text-white">
                <a href={whatsappUrl} target="_blank" rel="noopener noreferrer"><MessageCircle className="w-5 h-5" /> WhatsApp Chat</a>
              </Button>
              <Button
                size="lg"
                className="bg-[#229ED9] hover:bg-[#1b87bb] text-white"
                onClick={handleTelegram}
                disabled={sendingTelegram}
              >
                {sendingTelegram ? <Loader2 className="w-5 h-5 animate-spin" /> : <Send className="w-5 h-5" />}
                {sendingTelegram ? 'Sending…' : 'Notify on Telegram'}
              </Button>
              <Button asChild size="lg" variant="outline">
                <a href={emailUrl} target="_blank" rel="noopener noreferrer"><Mail className="w-5 h-5" /> Email Support</a>
              </Button>
            </div>
            <Button asChild size="lg" variant="hero" className="mt-3">
              <a href={whatsappUrl} target="_blank" rel="noopener noreferrer">
                <CalendarCheck className="w-5 h-5" /> 👉 Book a Free Consultation
              </a>
            </Button>
          </div>
        </div>
      )}
    </div>
  );
};
